# site settings
title: AI Risk Discussions
subtitle: 
email: youremailaddress@gmail.com
description: AI Risk Discussions (AIRD) facilitates discussion and evaluation of the risks from advanced AI. Our current focus is on soliciting expert evaluation of the arguments, understanding researcher perspectives via one-on-one conversations, and providing resources for interested stakeholders.
baseurl: "/aird" # the subpath of your site, e.g. /blog
url: https://michaelkeenan.github.io # the base hostname & protocol for your site
author:

permalink: /:title

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- /tools/*
